 version: '3.8'
 services:
  parser-api:
    container_name: parser-api
    depends_on:
      - parser-database
    image: latest
    build:
      context: .
    env_file: .env
    restart: unless-stopped
    ports:
      - '8000:8000'
    networks:
      - 'default'

  parser-database:
    container_name: parser-database
    image: postgres:14-alpine3.18
    build:
      context: .
    env_file: .env
    volumes:
      - C:/Users/prodg/IdeaProjects/parser_web_api/pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - '5555:5432'
    networks:
      - 'default'