 version: '3.8'
 services:
  parser-api:
    container_name: parser-api
    depends_on:
      - parser-database
    image: latest
    build:
      context: .
    env_file: .env
    volumes:
#DEPLOY      - /home/mae_parser_web_api/logs/logs.log:/app/logs/logs.log
    - ./logs/logs.log:/app/logs/logs.log
    restart: unless-stopped
    ports:
      - '8000:8000'
    networks:
      - 'default'

  parser-database:
    container_name: parser-database
    image: postgres:14-alpine3.18
    build:
      context: .
    env_file: .env
    volumes:
  #DEPLOY  - /home/mae_parser_web_api/pg_data:/var/lib/postgresql/data
      - ./pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - '5555:5432'
    networks:
      - 'default'