"""init

Revision ID: 910cbf4331b6
Revises: 
Create Date: 2023-11-07 00:03:28.644660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910cbf4331b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('square', sa.Float(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('total_floor', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('repair', sa.String(), server_default='repair', nullable=True),
    sa.Column('is_new_building', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('price_uye', sa.Float(), nullable=True),
    sa.Column('price_uzs', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flats')
    # ### end Alembic commands ###
