"""add land and commerce tables

Revision ID: da5a34e21431
Revises: 0be1da21660b
Create Date: 2023-12-03 02:20:38.528919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5a34e21431'
down_revision: Union[str, None] = '0be1da21660b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commerces',
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('square', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('type_of_commerce', sa.String(), nullable=True),
    sa.Column('price_uye', sa.Float(), nullable=True),
    sa.Column('price_uzs', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('external_id')
    )
    op.create_table('lands',
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('square', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('location_feature', sa.String(), nullable=True),
    sa.Column('type_of_land', sa.String(), nullable=True),
    sa.Column('price_uye', sa.Float(), nullable=True),
    sa.Column('price_uzs', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('external_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lands')
    op.drop_table('commerces')
    # ### end Alembic commands ###
